version: "3"
services:
  dbserver:
    container_name: spring_database
    image: mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      # DBの永続化
      - mysql_db:/var/lib/mysql


  app:
    container_name: spring
    build: .
    depends_on:
      # dbserverが起動してから、appを起動
      - dbserver
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    environment:
      # mysqlの接続設定 host:portはコンテナ名指定
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://dbserver/database"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
# DBの永続化先
volumes:
  mysql_db:
    driver: local